#!/bin/bash

sudo apt-get install libusb-1.0-0-dev
gcc -o usb_hub_power_cycle realtek_hub_power_cycle.c -lusb-1.0
sudo mv usb_hub_power_cycle /usr/local/bin/
sudo cp usb_hub_power_cycle.sh /usr/local/bin/
sudo chmod u+x /usr/local/bin/usb_hub_power_cycle
sudo chmod u+x /usr/local/bin/usb_hub_power_cycle.sh

sudo cp usb_hub_power_cycle.service /lib/systemd/system/usb_hub_power_cycle.service
sudo chmod 755 /lib/systemd/system/usb_hub_power_cycle.service

sudo systemctl daemon-reload
sudo systemctl enable usb_hub_power_cycle.service
